# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CICD pipeline for springboot project 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Build-and-Push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: temurin
        server-id: docker.io
        server-username: DOCKER_USERNAME
        server-password: DOCKER_PASSWORD      
    - name: Building and pushing User service
      run: mvn package dockerfile:push --file user-service/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Department service
      run: mvn package dockerfile:push --file department-service/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Cloud config server service
      run: mvn package dockerfile:push --file cloud-config-server/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Cloud gateway
      run: mvn package dockerfile:push --file cloud-gateway/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Hystrix Dashboard
      run: mvn package dockerfile:push --file hystrix-dashboard/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Service Registry 
      run: mvn package dockerfile:push --file service-registry/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


         

    
    
    
    
    
    
    
    
    
    
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
