# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: CICD pipeline for springboot project 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: cluster-springboot
  GKE_ZONE: us-central1-c

jobs:
  Build-and-Push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'   
    - name: Building User service
      run: mvn package -f user-service/pom.xml
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image
      run: |
        docker build -t madhu1607/user-service:latest .
        docker push madhu1607/user-service:latest    
    - name: Building and pushing Department service
      run: mvn package dockerfile:push --file department-service/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Cloud config server service
      run: mvn package dockerfile:push --file cloud-config-server/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Cloud gateway
      run: mvn package dockerfile:push --file cloud-gateway/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Hystrix Dashboard
      run: mvn package dockerfile:push --file hystrix-dashboard/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building and pushing Service Registry 
      run: mvn package dockerfile:push --file service-registry/pom.xml
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  Deploy:
    needs: Build-and-Push-to-dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GKE_KEY }}
        CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
        ZONE_NAME: ${{ env.GKE_ZONE }}
      with:
        args: apply -f deployments/


         

    
    
    
    
    
    
    
  
